### ISSUE TITLE
Blue belt activities

### ISSUE THREAD

**Issue by mvollmary** [AppSecure-nrw/security-belts#17]
DAST
Threat Modeling
Awareness

- [x] Conduction of threat modelling
  - STRIDE
  - *requires* understanding of company security policies
  - *includes* Regularly review the security mechanisms of your architecture
- [x] Approval by reviewing any new version // Code Review on all changes (Yellow Security Code review: add 'on each code change')
  - *requires* Security Champion knowledge
- [x] PII (personally identifiable information) logging concept
- [x] Basic Scan
  - *tools* Burp, ZAP
  - *includes* [OWASP Testing Guide 4.5.2](https://owasp.org/www-project-web-security-testing-guide/v42/4-Web_Application_Security_Testing/05-Authorization_Testing/01-Testing_Directory_Traversal_File_Include.html)
- [x] API Fuzzing
  - *requires* Simple Scan
  - *tools* Burp/ZAP + OpenApi/Swagger
  - *includes* Coverage of hidden endpoints (word list)
- [x] Load tests
- [x] Testing for Bypassing Authentication Schema
  - *tools* gobuster, dirbuster
  - use OpenAPI
  - [OWASP Testing Guide 4.4.4](https://owasp.org/www-project-web-security-testing-guide/v42/4-Web_Application_Security_Testing/04-Authentication_Testing/04-Testing_for_Bypassing_Authentication_Schema.html)
- [x] Advanced Mob-Hacking
  - include usage of tools like Burp
- [x] Get to know your Design Flaws
       releated: Get to know Security by Design Principles

**Comment by wurstbrot** [comment]
I like " Testing for Bypassing Authentication Schema". Maybe you add OpenAPI here, too.

Do you have a description?

**Comment by wurstbrot** [comment]
"Approval by reviewing any new version" is not clear to me, but I assume you will add a description later.

**Comment by bob5ec** [comment]
@wurstbrot: See [DSOMM: Approval by reviewing any new version](https://dsomm.timo-pagel.de/detail.php?dimension=Culture+and+Org.&subdimension=Process&element=Approval+by+reviewing+any+new+version) 😁
