### ISSUE TITLE
Green belt activities

### ISSUE THREAD

**Issue by mvollmary** [AppSecure-nrw/security-belts#18]
- [x] Environment depending configuration parameters
- [x] Nightly Dependency (Software Library) Version Upgrade.
  - For example check for latest libraries, run tests, create pull request, team accept/rejects PR
- [x] Static analysis for all self written components
  - *tools* contrast, spotbugs, sonarqube, Amazon CodeGuru
  - *includes* input validation testing, output security requirements, [OWASP Testing Guide 4.9.4](https://owasp.org/www-project-web-security-testing-guide/v42/4-Web_Application_Security_Testing/09-Testing_for_Weak_Cryptography/04-Testing_for_Weak_Encryption.html)
- [x] Treatment of defects with high accuracy and high criticality
  - Independed of SAST & DAST
- [x] Integration of vulnerability issues into the development process
- [x] Stored Secrets
  - Testing of Key Management, Usage of pre-commit hooks in git
  - *tools* trufflehog, gitrob, sonarqube
- [x] Test security configuration of infrastructure
  - Also CIS for VMs, OS, Middleware, Appserver, Datenbank, ... 
- [x] Test security configuration of cloud environments: 
  - AWS / Azure, IAM, Buckets, ...
- [x] Test of Container Images Regarding Known Vulnerabilities
- [x] Do you identify and remove systems, applications, application dependencies, or services that are no longer used, have reached end of life, or are no longer actively developed or supported?
- [x] Testing for Default Credentials
  - *tools* hydra, nmap
  - [OWASP Testing Guide 4.4.2](https://owasp.org/www-project-web-security-testing-guide/v42/4-Web_Application_Security_Testing/04-Authentication_Testing/02-Testing_for_Default_Credentials.html)

**Comment by mvollmary** [comment]
Candidate for orange belt:
- Test for Default Credentials
- Prevent Secrets in Source Code

**Comment by mvollmary** [comment]
Following activity removed:
- [ ] Are vendors aligned with standard security controls and software development tools and processes that the organization utilizes?
  - *requires* Do vendors meet the security responsibilities and quality measures of service level agreements defined by the organization?

Assessments by teams do not create value once the contract with vendors is done. Solution, once the Security Belts are an established model, should include vendor assessments on Security Belts during contract negotiation.
