### ISSUE TITLE
Security By Design Activities

### ISSUE THREAD

**Issue by mvollmary** [AppSecure-nrw/security-belts#28]
## Orange
- [x] Creation of Evil User Stories
- [x] Get to know Security by Design Principles
  *Assessment*: jeopardy
  1. Secure the Weakest Link
  2. Defense in Depth 
  3. Fail-safe Defaults
  4. Least Privilege
  5. Compartmentalization
  6. Be Reluctant to Trust
  7. Separation of Privilege
  8. Keep It Simple
       - Keep it simple: Simple Code
    *tools*: checkstyle, pwd/cpd
    *includes*: Code duplication, Code conventions, Craftsmanship
     - Keep it simple: Simple Design
    *includes*: Service Design, System cut, Single Responsibility (Microservices, Least privileges')
  9. Open Design
  10. Complete Mediation
  11. Do not reinvent the wheel
        Do not build own Parser, Unparser, Crypto, Data languages, protocols
        Use mainstream technology like OpenAPI for REST
  12. TODO
- [x] Explain the two design principles Never invent security technology and Don't trust your supply chain

## Approach
- [x] Read and extract activities
  - [Related Work in Lars' Diss page 28](https://se-rwth.de/phdtheses/Diss-Hermerschmidt-Agile-Modellgetriebene-Entwicklung-von-Software-Security-and-Privacy.pdf)
    - [Related Work lesen](https://scholar.google.de/scholar?start=10&hl=de&as_sdt=2005&sciodt=0,5&cites=12187179507406448382&scipsc=)

**Comment by mvollmary** [comment]
- Do not reinvent the wheel
  Do not build own Parser, Unparser, Crypto, Data languages, protocols
- Keep it simple: Simple Code
  *tools*: checkstyle, pwd/cpd
  *includes*: Code duplication, Code conventions, Craftsmanship
- Keep it simple: Simple Design
  *includes*: Service Design, System cut, Single Responsibility (Microservices, Least privileges')
